[package]
name = "_07_managing_projects"
version = "0.1.0"
authors = ["Seong Hoon Wee <mrgravity817@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
